services:
    presentation:
        build:
            context: .
            target: presentation
        ports:
            - '8000:8000'
        read_only: true
        tmpfs:
            - /tmp
            - /var/cache/nginx
            - /var/run

    admin:
        build:
            context: .
            target: admin
        ports:
            - '127.0.0.1:3001:3001'
        environment:
            HOST: 0.0.0.0
            PORT: 3001
        command: node manage/server.js
        volumes:
            - .:/app
        profiles:
            - admin
